default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: libmarks_development
  #username: libmarks
  #password:
  #host: localhost
  #port: 5432
  #schema_search_path: myapp,sharedapp,public
  # Defaults to warning.
  #min_messages: notice

test:
  <<: *default
  database: libmarks_test

# production:
#   url: <%= ENV['DATABASE_URL'] %>

production:
  <<: *default
  database: libmarks_production
  password: <%= ENV['LIBMARKS_DATABASE_PASSWORD'] %>
